language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:  
    - "node_modules"
script: true
before_deploy: yarn add now
deploy:
  - provider: script
    skip_cleanup: true
    script: now -t $NOW_TOKEN && now alias -t $NOW_TOKEN
    on:
      master: true
      