language: node_js
node_js:
- node
cache:
  yarn: true
  directories:
  - node_modules
script: true
before_deploy: yarn add now
deploy:
- provider: script
  skip_cleanup: true
  script: now rm roadster-server -y -t $NOW_TOKEN && now -t $NOW_TOKEN && now alias -t $NOW_TOKEN
  on:
    master: true
before_install:
- openssl aes-256-cbc -K $encrypted_f2b07ff905e3_key -iv $encrypted_f2b07ff905e3_iv
  -in .env.production.enc -out .env.production -d
