language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:  
    - "node_modules"
script: true
before_deploy: yarn add now
deploy:
  - provider: script
    script: yarn deploy
    on:
      master: true